version: '3.8'

services:
  # Development service
  eat-fast-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host 0.0.0.0
    networks:
      - eat-fast-network
    
  # Production service
  eat-fast-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=https://your-backend-api.com/api/v1
    networks:
      - eat-fast-network
    profiles:
      - production
    
  # Nginx reverse proxy for production
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - eat-fast-prod
    networks:
      - eat-fast-network
    profiles:
      - production

networks:
  eat-fast-network:
    driver: bridge