version: '3.8'

services:
  eat-fast-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eat-fast-frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
