services:
  - type: web
    name: eat-fast
    env: node
    plan: free
    buildCommand: NODE_OPTIONS="--max-old-space-size=1024" npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://your-backend-url.com/api/v1
    domains:
      - eat-fast-app.onrender.com