// Translations se trouvaient dans clients_layout
 export const translations = {
  fr: {
    dashboard: 'Tableau de bord',
    welcome: 'Bienvenue',
    orders: 'Commandes',
    profile: 'Profil',
    support: 'Support',
    notifications: 'Notifications',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    darkMode: 'Mode sombre',
    lightMode: 'Mode clair',
    french: 'Français',
    english: 'Anglais',
    myOrders: 'Mes Commandes',
    trackOrder: 'Suivre ma commande',
    orderHistory: 'Historique',
    totalOrders: 'Total Commandes',
    avgDelivery: 'Livraison Moy.',
    satisfaction: 'Satisfaction',
    lastOrder: 'Dernière commande',
    activeOrder: 'Commande active',
    recentActivity: 'Activité récente',
    quickActions: 'Actions rapides',
    orderNow: 'Commander maintenant',
    viewMenu: 'Voir le menu',
    contactSupport: 'Contacter le support',
    restaurants: 'Restaurants',
    cart: 'Panier',
    chatSupport: "Discussion avec le support"

  },
  en: {
    dashboard: 'Dashboard',
    welcome: 'Welcome',
    orders: 'Orders',
    profile: 'Profile',
    support: 'Support',
    notifications: 'Notifications',
    settings: 'Settings',
    logout: 'Logout',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    french: 'French',
    english: 'English',
    myOrders: 'My Orders',
    trackOrder: 'Track Order',
    orderHistory: 'Order History',
    totalOrders: 'Total Orders',
    avgDelivery: 'Avg Delivery',
    satisfaction: 'Satisfaction',
    lastOrder: 'Last Order',
    activeOrder: 'Active Order',
    recentActivity: 'Recent Activity',
    quickActions: 'Quick Actions',
    orderNow: 'Order Now',
    viewMenu: 'View Menu',
    contactSupport: 'Contact Support',
    restaurants: 'Restaurants',
    cart: 'Cart',
    chatSupport: "Chat with Support"
 }
};
